import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import AppSideBar from "@/components/other/Navigation/AppSidebar";
import { ThemeProvider } from "@/components/other/themeProvider";
import NavBar from "@/components/other/Navigation/NavBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex justify-baseline items-baseline h-screen `}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <AppSideBar />
          <main className="pl-[16rem] p-4 w-full h-full">
            <NavBar/>
            {children}
            </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
